name: chemspax
channels:
     - conda-forge
     - anaconda
     - defaults
dependencies:
     - python=3.7.9
     - numpy==1.19.1
     - pandas==1.1.3
     - ase
     - openbabel==3.1.1
     - pip
     - sphinx
     pip:
          - myst-parser
          - sphinx-rtd-theme
