name: chemspax
channels:
     - conda-forge
     - anaconda
     - defaults
dependencies:
     - python=3.10.5
     - ase=3.22.1
     - openbabel=3.1.1
     - pandas=1.4.3
     - numpy=1.23.2
     - openpyxl
     - pip
     - sphinx
     - pip:
          - myst-parser
          - sphinx-rtd-theme
